"""Application configuration."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class Config:
    SECRET_KEY = "dev-secret-change-in-production"   # enables flash messages / sessions
    # SQLite file at the repo root; regenerated by scripts/seed.py (M1).
    DATABASE_URL = f"sqlite:///{ROOT / 'app.db'}"
    # Where uploaded documents are stored at runtime.
    UPLOAD_DIR = ROOT / "uploads"
    # Committed test documents (used by seed/demo and tests).
    FIXTURES_DIR = ROOT / "tests" / "fixtures"


class TestConfig(Config):
    DATABASE_URL = "sqlite:///:memory:"
