"""
Generate the committed test-fixture set from the IRS templates + our synthetic scenario data.

Decision recap (see docs/02):
  - 1040s and Rivera W-2s are GENERATED by filling the official IRS AcroForm templates
    (reproducible, real layout, extractable via tier-1 form fields).
  - The one real vendor sample (ADP earnings summary, text-layer) is copied in as-is; being
    Tara Wilson / 2018 it doubles as an authentic wrong-year + unknown-person fixture.
  - The "unreadable scan" is a filled W-2 rasterized to an image-only PDF (0 text, no fields).

Prereq:  ./venv/Scripts/python.exe scripts/fetch_samples.py
Run:     ./venv/Scripts/python.exe scripts/build_fixtures.py
Output:  tests/fixtures/*.pdf  (+ MANIFEST.md)
"""
from __future__ import annotations

import io
import shutil
from pathlib import Path

from pypdf import PdfReader, PdfWriter
from pypdf.generic import BooleanObject, NameObject

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "data" / "templates"
FIXTURES = ROOT / "tests" / "fixtures"
ADP_SAMPLE = ROOT / "sampleData" / "W2_Multi_Sample_Data_input_ADP1_clean_15500.pdf"

# --- Per-template positional field maps (fields are opaque f*_NN; located by coordinates) ---
# W-2 CopyB (the employee's copy — what a client sends). Same across 2023/2025 templates.
W2_COPYB = {
    "ssn": "f2_01[0]", "employer_ein": "f2_02[0]", "employer_name": "f2_03[0]",
    "employee_first": "f2_05[0]", "employee_last": "f2_06[0]", "box1_wages": "f2_09[0]",
}
# 1040 name row (same across 2023/2024 templates).
F1040 = {
    "taxpayer_first": "f1_04[0]", "taxpayer_last": "f1_05[0]", "taxpayer_ssn": "f1_06[0]",
    "spouse_first": "f1_07[0]", "spouse_last": "f1_08[0]", "spouse_ssn": "f1_09[0]",
}


def _prepare_writer(reader: PdfReader) -> PdfWriter:
    writer = PdfWriter()
    writer.append(reader)
    acro = writer._root_object["/AcroForm"]
    if "/XFA" in acro:                                    # XFA would shadow AcroForm values
        del acro["/XFA"]
    acro[NameObject("/NeedAppearances")] = BooleanObject(True)
    return writer


def _apply(writer: PdfWriter, values: dict) -> None:
    for page in writer.pages:
        try:
            writer.update_page_form_field_values(page, values, auto_regenerate=False)
        except Exception:
            pass


def _fq(reader: PdfReader, short: str, must_contain: str | None = None) -> str:
    """Resolve a short field name (e.g. 'f2_05[0]') to its fully-qualified name."""
    for k in reader.get_fields():
        if k.endswith(short) and (must_contain is None or must_contain in k):
            return k
    raise KeyError(f"{short} (contains={must_contain})")


def _copyb_page_index(reader: PdfReader) -> int:
    for i, page in enumerate(reader.pages):
        for annot in (page.get("/Annots") or []):
            obj, name = annot.get_object(), ""
            while obj is not None:
                t = obj.get("/T")
                name = (str(t) + "." + name) if t else name
                parent = obj.get("/Parent")
                obj = parent.get_object() if parent else None
            if "CopyB" in name:
                return i
    raise RuntimeError("CopyB page not found")


def build_w2(template: Path, data: dict, out: Path) -> None:
    """Fill the W-2 CopyB, then keep only that single page for a compact fixture."""
    reader = PdfReader(str(template))
    values = {_fq(reader, W2_COPYB[k], "CopyB"): v for k, v in data.items() if k in W2_COPYB}
    writer = _prepare_writer(reader)
    _apply(writer, values)

    buf = io.BytesIO()
    writer.write(buf)
    buf.seek(0)
    filled = PdfReader(buf)
    page_idx = _copyb_page_index(filled)
    single = PdfWriter()
    single.append(filled, pages=[page_idx])
    with open(out, "wb") as fh:
        single.write(fh)


def build_1040(template: Path, data: dict, out: Path) -> None:
    reader = PdfReader(str(template))
    values = {_fq(reader, F1040[k]): v for k, v in data.items() if k in F1040}
    writer = _prepare_writer(reader)
    _apply(writer, values)
    with open(out, "wb") as fh:
        writer.write(fh)


def rasterize_unreadable(src_pdf: Path, out: Path) -> None:
    """Render a filled W-2 to a flat image-only PDF: no text layer, no form fields."""
    import pypdfium2 as pdfium

    pdf = pdfium.PdfDocument(str(src_pdf))
    img = pdf[0].render(scale=1.4).to_pil().convert("RGB")
    img.save(str(out))


# --- Fixture recipes (synthetic Rivera-scenario data) ---
def main() -> None:
    FIXTURES.mkdir(parents=True, exist_ok=True)
    w25, w23 = TEMPLATES / "fw2--2025.pdf", TEMPLATES / "fw2--2023.pdf"
    t1040_24, t1040_23 = TEMPLATES / "f1040--2024.pdf", TEMPLATES / "f1040--2023.pdf"

    built = []

    # W-2s (SSNs are digits-only so the comb boxes render correctly)
    build_w2(w25, dict(employee_first="Ana", employee_last="Rivera", ssn="111223333",
                       employer_name="Northwind Traders", employer_ein="11-1111111",
                       box1_wages="82000.00"), FIXTURES / "w2_ana_emp1_2025.pdf")
    build_w2(w25, dict(employee_first="Ana", employee_last="Rivera", ssn="111223333",
                       employer_name="Contoso Ltd", employer_ein="22-2222222",
                       box1_wages="15500.00"), FIXTURES / "w2_ana_emp2_2025.pdf")
    build_w2(w25, dict(employee_first="Luis", employee_last="Rivera", ssn="444556666",
                       employer_name="Fabrikam Inc", employer_ein="33-3333333",
                       box1_wages="68000.00"), FIXTURES / "w2_luis_2025.pdf")
    build_w2(w25, dict(employee_first="Carlos", employee_last="Mendez", ssn="777889999",
                       employer_name="Globex Corp", employer_ein="44-4444444",
                       box1_wages="50000.00"), FIXTURES / "w2_carlos_2025.pdf")   # unknown person
    build_w2(w23, dict(employee_first="Ana", employee_last="Rivera", ssn="111223333",
                       employer_name="Northwind Traders", employer_ein="11-1111111",
                       box1_wages="80000.00"), FIXTURES / "w2_ana_2023.pdf")       # wrong year
    built += ["w2_ana_emp1_2025.pdf", "w2_ana_emp2_2025.pdf", "w2_luis_2025.pdf",
              "w2_carlos_2025.pdf", "w2_ana_2023.pdf"]

    # 1040s (household level; SSNs digits-only)
    rivera_1040 = dict(taxpayer_first="Ana", taxpayer_last="Rivera", taxpayer_ssn="111223333",
                       spouse_first="Luis", spouse_last="Rivera", spouse_ssn="444556666")
    build_1040(t1040_24, rivera_1040, FIXTURES / "f1040_rivera_2024.pdf")          # prior-year return
    build_1040(t1040_23, rivera_1040, FIXTURES / "f1040_rivera_2023.pdf")          # wrong year
    built += ["f1040_rivera_2024.pdf", "f1040_rivera_2023.pdf"]

    # Real vendor text-layer sample (doubles as wrong-year 2018 + unknown-person Tara)
    if ADP_SAMPLE.exists():
        shutil.copyfile(ADP_SAMPLE, FIXTURES / "w2_textlayer_adp_tara_2018.pdf")
        built.append("w2_textlayer_adp_tara_2018.pdf")

    # Unreadable scan (image-only)
    rasterize_unreadable(FIXTURES / "w2_ana_emp1_2025.pdf", FIXTURES / "scan_unreadable.pdf")
    built.append("scan_unreadable.pdf")

    _write_manifest(built)
    print(f"built {len(built)} fixtures -> {FIXTURES.relative_to(ROOT)}")


def _write_manifest(names: list[str]) -> None:
    lines = ["# Test fixtures (generated by scripts/build_fixtures.py)\n",
             "Do not edit by hand — regenerate. Purpose of each file:\n"]
    purpose = {
        "w2_ana_emp1_2025.pdf": "Ana W-2 #1 (Northwind) — clean tier-1 auto-match (C1)",
        "w2_ana_emp2_2025.pdf": "Ana W-2 #2 (Contoso) — fills slot #1 in arrival order (C2)",
        "w2_luis_2025.pdf": "Luis W-2 (Fabrikam) — baseline job",
        "w2_carlos_2025.pdf": "W-2 for Carlos Mendez — unknown person (C5)",
        "w2_ana_2023.pdf": "Ana W-2 on 2023 template — wrong year (C4)",
        "f1040_rivera_2024.pdf": "Rivera joint 1040, TY2024 — prior-year return, should MATCH (C8)",
        "f1040_rivera_2023.pdf": "Rivera 1040, TY2023 — wrong year (C9)",
        "w2_textlayer_adp_tara_2018.pdf": "Real ADP earnings-summary (text layer); wrong-year+unknown-person",
        "scan_unreadable.pdf": "Image-only render — unreadable (C6)",
    }
    for n in names:
        lines.append(f"- `{n}` — {purpose.get(n, '')}")
    (FIXTURES / "MANIFEST.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
